### ISSUE TITLE
Error while generating

### ISSUE THREAD

**Issue by Huc91** [JuanPotato/Tofu#1]
Launched on my shell
`python gen_tofu.py 0000 FFFD -o`

Results in an error:
File "gen_tofu.py", line 7
SyntaxError: Non-ASCII character '\xf0' in file gen_tofu.py on line 7, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I needed to remove the comment on line 7

**Comment by JuanPotato** [comment]
Yeah my bad. That comment isn't all that needed lol.

**Comment by Huc91** [comment]
No no it's the most important thing :-D
