### ISSUE TITLE
Make better tofu template

### ISSUE THREAD

**Issue by receptor** [JuanPotato/Tofu#5]
If you leave out the frame, you will have space to make the numbers more readable

**Comment by JuanPotato** [comment]
So just free floating numbers? I could still include the frame, but have it much thinner. And I could do the same with the whitespace along the edges.

this looks decent
![image](https://user-images.githubusercontent.com/9531780/29008305-85cf7300-7ae2-11e7-9589-17bf30c1ae21.png)

**Comment by receptor** [comment]
Yes, this looks great :)

**Comment by pvinis** [comment]
also check how https://github.com/be5invis/Iosevka is made, if you want to replace fontforge.

**Comment by JuanPotato** [comment]
@pvinis Will take a look at that, looks really nice.

fixed with 3263a01
